lankuai/lankuai/lkitsm/project/avi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views
from django.urls import re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
# from project.settings import MEDIA_ROOT
from project import settings

urlpatterns = [
                  # 门必须得锁紧，课堂首页显示视频，有分页所以需要加上页码
                  url(r'^(\d+)$', views.media),

                  # 上传
                  url(r'^upload$', views.form),

                  # 某视频
                  url(r'^avi(\d+)$', views.avi),

                  url(r'^add(\d+)$', views.addIsee),

                      # 主页，更多 more
                  url(r'^addok$', views.addok),

                  url(r'^media/(?P<path>.*)/$', serve, {'document_root': settings.MEDIA_ROOT}),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lankuai/lankuai/lkitsm/project/project/urls.py
from django.contrib import admin
from django.urls import path,include
import xadmin

urlpatterns = [
    # 系统自带后台 admin
    #path('admin/', admin.site.urls),

    # 使用xadmin后台
    path('admin/' ,xadmin.site.urls),

    #login
    path(r'', include('login.urls')),
    #工单系统
    path(r'', include('website.urls')),
    #蓝快课堂
    path(r'media/', include('avi.urls')),

    #人事管理 之工作流1
    path(r'hrworkfolw/', include('workfolw.urls')),
    #人事管理 之工作流2
    path(r'mrworkfolw/', include('workfolw.urls')),
    #人事管理 之公告管理
    path(r'', include('workfolw.urls')),

    #商务管理
    path(r'business/', include('business.urls')),

    #维修 ，采购 repairANDbuyer
    path(r'repairANDbuyer/', include('repairANDbuyer.urls')),

    #path('', include('workflow-master.urls')),

#(r'^site_media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_PATH}),
]

lankuai/lankuai/lkitsm/project/avi/models.py
from django.db import models


# 展示视频，存取视频
class Video(models.Model):
    uploader = models.CharField(r'上传者', max_length=20)
    imgpath = models.ImageField(upload_to='img')  #
    uppath = models.FileField(upload_to='uppath')  # 定义上传路径
    describe = models.CharField(r'标题', max_length=100)
    uploaddate = models.DateField(r'上传日期', auto_now_add=True)
    kind = models.CharField(r'所属种类', max_length=20)
    score = models.IntegerField(r'观看该影片可得分数')
    haveseen = models.CharField(r'看过没呀', max_length=20, default="未睇过")
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.uploader
    class Meta:
        verbose_name = '展示存取视频'
        verbose_name_plural = '展示存取视频'
        db_table = 'video'
    @classmethod
    def createvideo(cls, upl, img, upp, des, uploadd, ki, isD=False):
        v = cls(uploader=upl, imgpath=img, uppath=upp, describe=des, uploaddate=uploadd, kind=ki)
        return v

#分数表
class Grade(models.Model):
    gname = models.CharField(r'用户', max_length=20)
    gid = models.IntegerField(r'视频ID')
    gtotal = models.IntegerField(r'总分数')
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.gtotal
    class Meta:
        verbose_name = '计算分数'
        verbose_name_plural = '计算分数'
        db_table = 'Grade'
    @classmethod
    def creategrade(cls ,name ,id ,total ,isD = False):
        g = cls(gname=name ,gid=id ,gtotal=total)
        return g

#谁看过
class Isee(models.Model):
    iname = models.CharField(r'用户', max_length=20)
    igid = models.IntegerField(r'视频ID')
    iseetime = models.DateField(r'观看时间' ,auto_now_add=True)
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.iname
    class Meta:
        verbose_name = '睇过未'
        verbose_name_plural = '睇过未'
        db_table = 'Isee'
    @classmethod
    def createisee(cls ,name ,gid ,seetime ,isD = False):
        isee = cls(iname=name ,igid=gid ,iseetime=seetime)
        return isee

lankuai/lankuai/lkitsm/project/avi/views.py
from django.shortcuts import render , redirect
from django.core.paginator import Paginator
from django import forms
from .models import Video
from django.http import HttpResponse, HttpResponseRedirect


class videoForm(forms.Form):
    uploader = forms.CharField()
    imgpath = forms.ImageField()
    uppath = forms.FileField()
    describe = forms.CharField()
    uploaddate = forms.DateField()
    kind = forms.CharField()
    score = forms.IntegerField()
    haveseen = forms.CharField()

#form表单
def form(request):

    if request.method == 'POST':

        vf = videoForm(request.POST ,request.FILES)
        if vf.is_valid():

            uploader = vf.cleaned_data['uploader']
            imgpath = vf.cleaned_data['imgpath']
            print(uploader)
            uppath = vf.cleaned_data['uppath']
            print(uppath ,"+++++++++++++++++++++++++++++++++++++++++++++++++")
            describe = vf.cleaned_data['describe']
            print(describe)
            uploaddate = vf.cleaned_data['uploaddate']
            print(uploaddate)
            kind = vf.cleaned_data['kind']
            print(kind)
            score = vf.cleaned_data['score']
            print(score,'5555555555555555555555555555555555555555555555')
            haveseen = vf.cleaned_data['haveseen']


            vid = Video()
            vid.uploader = uploader
            vid.imgpath = imgpath
            vid.uppath = uppath
            vid.describe = describe
            vid.uploaddate = uploaddate
            vid.kind = kind
            vid.score = score
            vid.haveseen = haveseen

            print(type(vid.uppath), '---' ,vid.uppath ,"11111111111111111111111111111111111111111111111111111111111111111111111111111111")
            vid.save()
            print("2222222222222222")
            print("来到这里会重定向-----------------")
        return redirect('/media/upload')
    else:
        vf = videoForm

    haveseen = "已看过"
    print("怎么没到这历来。。。。。。。。。。。。。。。。。。。。。。。。。")

    return render(request, 'avi/uploading.html', locals() ,{"title":"上传视频","haveseen":haveseen})




from project.settings import MEDIA_URL
#蓝快课堂
def media(request ,pageid):

    username = request.session['username']
    print(username ,'======当前登录用户名username========================')
    vidList = Video.objects.all()
    paginator = Paginator(vidList, 3)
    page = paginator.page(pageid)
    print(page ,'页数')
    #搜索
    search = request.POST.get("search")
    error_msg = "查无此视频"

    #我的总分
    #我看过的视频ID，所有ID的分数和
    iseeList = Isee.objects.filter(iname=username)
    count = 0
    score = 0
    for isee in iseeList:

        v = Video.objects.get(id=isee.igid)#取出我看过的视频
        print(v.score ,"单条视频的分数")
        count += 1
        score += v.score
        print(score ,"所有视频的分数和")

    if not search:
        error_msg="请输入关键字"
        return render(request, 'avi/media.html', {'title': '蓝快课堂', 'username': username, 'video': page, 'vidList': vidList, 'error_msg': error_msg , "count":count , "score":score})
    else:

        vidList1 = Video.objects.filter(describe__icontains = search)
        return render(request, 'avi/media.html', {'title': '蓝快课堂', 'username': username, 'video': page, 'vidList': vidList1, 'error_msg': error_msg , "count":count , "score":score})


def avi(request ,id):

    video = Video.objects.get(id = id)

    return render(request ,'avi/avi.html' ,{"video":video})

import time
from .models import Isee
def addIsee(request ,pid):
    #当前用户
    username = request.session['username']
    print(username)
    #视频ID
    newpath = request.path[10:]#media/add1
    video = Video.objects.get(id=newpath)
    print(request.path ,"----------------------url----------------------")
    print(newpath ,"新dizhi --------------------------------------------")
    seetime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time()))
    print(seetime ,"")
    #如果该用户看过该视频，则直接重定向
    if Isee.objects.filter(iname=username ,igid=newpath):
        return redirect('/media/avi' + newpath)
    else:
        #否则先存进去再重定向
        isee = Isee.createisee(username, newpath, seetime)
        isee.save()
        return HttpResponseRedirect('http://127.0.0.1:8000/media/avi' + newpath)


def addok(request):
    return redirect('/addok')

lankuai/lankuai/lkitsm/project/templates/avi/avi.html
{% extends 'base.html' %}

{% block title %}我的代办{% endblock %}


{% block linkscript %}

{% endblock %}


{% block navigationbar %}

	<div class="row clearfix">
		<div class="col-md-12 column">
			<ul class="breadcrumb">
				<li>
					 <a href="/index">首页</a>
				</li>
				<li>
					 <a href="/media/1">蓝快视频</a>
				</li>
				<li class="active">
					播放视频
				</li>
			</ul>
		</div>
	</div>

    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <div class="thumbnail">
                    <div class="caption">
                        <video id={{ video.id }} width="900" height="650" controls="controls">
                            <source type="video/mp4" src="media/{{ video.uppath }}">
                            您的浏览器不支持 HTML5 video 标签。
                        </video>

                        <p>上传日期：{{ video.uploaddate }}</p>
                        <!--              <p>上传人：{{ video.uploader }}</p>-->
                        <p>标题：{{ video.describe }}</p>
                        <p>分数：{{ video.score }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block content %}
    <script>
        var video = document.getElementById({{ video.id }});
        video.addEventListener('ended', function () {
            //window.location.href = 'http://127.0.0.1:8000/media/avi{{ video.id }}';
            //setTimeout(window.open("/media/add{{ video.id }}"),3000)
            window.location.href = "/media/add{{ video.id }}"
        }, false);
    </script>
{% endblock %}

lankuai/lankuai/lkitsm/project/templates/avi/media.html
<!-- 上传页面 -->


{% extends 'base.html' %}

{% block title %}我的代办{% endblock %}


{% block linkscript %}
    <style>
        .zoomImage {
            width: 100%;
            height: 0;
            padding-bottom: 100%;
            overflow: hidden;
            background-position: center center;
            background-repeat: no-repeat;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            background-size: cover;
        }
    </style>
{% endblock %}


{% block navigationbar %}

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                    </button>
                    <a class="navbar-brand" href="#">蓝色快线影视教学中心</a>
                </div>
                <form method="post" action="/media/1" class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input class="form-control" type="search" name="search"/>
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">

                    <li>
                        <a href="#">{{ username }}</a>
                    </li>
                    <li>
                        <a href="">观看数量:{{ count }}</a>
                    </li>
                    <li>
                        <a href="">学分:{{ score }}</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>


	<div class="row clearfix">
		<div class="col-lg-12 column">
			<ul class="breadcrumb">
				<li>
					 <a href="/index">首页</a>
				</li>
				<li class="active">
					蓝快视频
				</li>
			</ul>
		</div>
	</div>

{% endblock %}


{% block content %}


<div class="row clearfix">
    <div class="col-md-12 column" style="padding: 100px;">
        <div class="row">
            {% for item in vidList %}
                <div class="col-md-3">
                    <div class="thumbnail">
                        <div class="caption">
                            <a href="avi{{ item.id }}" >
                                <div class="zoomImage" style="background-image:url('media/{{ item.imgpath }}')"></div>
                                <!--<img class="zoomImage"  src="media/{{ item.imgpath }}">-->
                            </a>
                            您的浏览器不支持 HTML5 video 标签。
                            <p>上传日期：{{ item.uploaddate }}</p>
                            <p>标题：{{ item.describe }}</p>
                            <p>分数：{{ item.score }}</p>
                            <p>{{ item.haveseen }}</p><!--
                            <p>"media/{{ item.imgpath }}"</p>-->
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
</div>

<!-- 页码 -->
<div class="row clearfix">
    <div class="col-md-12 column text-center">
        <ul class="pagination">
            {% for index in video.paginator.page_range %}
                <li>
                    <a href="/media/{{ index }}">{{ index }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

lankuai/lankuai/lkitsm/project/templates/avi/uploading.html
<!-- 上传页面 -->


{% extends 'base.html' %}

{% block title %}上传视频{% endblock %}


{% block linkscript %}
    <!--时间控件样式-->
    <link rel="stylesheet" href="/static/css/bootstrap-laydate.css">
    <script src="/static/js/bootstrap-laydate.js"></script>

{% endblock %}


{% block navigationbar %}
    <div class="row clearfix">
        <div class="col-lg-12">


            <ul class="breadcrumb">
                <li>
                    <a href="/index">首页</a>
                </li>
                <li class="active">
                    上传视频
                </li>
            </ul>
        </div>
    </div>


    <div class="container">
        <div class="row clearfix">
            <form method="post" action="upload" enctype="multipart/form-data" class="needs-validation">


                <div class="col-md-4 column">
                    <label for="id_uploader">作者:</label>
                    <input class="form-control" type="text" name="uploader" required id="id_uploader">

                    <label for="id_kind">视频类型:</label>
                    <input class="form-control" type="text" name="kind" required id="id_kind">

                    <label for="id_uppath">视频路径:</label>
                    <input class="form-control" type="file" name="uppath" required id="id_uppath">

                </div>


                <div class="col-md-4 column">
                    <label for="id_describe">详细信息:</label>
                    <input class="form-control" type="text" name="describe" required id="id_describe">

                    <label for="id_score">观影可得分:</label>
                    <input class="form-control" type="text" name="score" required id="id_score">
                </div>


                <div class="col-md-4 column">
                    <label for="test1">上传日期:</label>
                    <input type="text" name="uploaddate" class="form-control" id="test1" placeholder="" required="">
                    <div class="invalid-feedback" style="display: none">
                        Zip code required.
                    </div>


                    <label for="id_imgpath">预览图:</label>
                    <input class="form-control" type="file" name="imgpath" required id="id_imgpath">
                </div>

                <div class="col-md-4 mb-3" style="display: none">
                    <label for="id_haveseen">看没看过:</label>
                    <input class="form-control" type="text" value={{ haveseen }} name="haveseen" required
                           id="id_haveseen" readonly="readonly">
                </div>

                <button class="btn btn-primary btn-lg btn-block" type="submit">上传</button>
            </form>
        </div>
    </div>
{% endblock %}



{% block content %}


    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';

            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');

                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>

    <script>
        //执行一个laydate实例
        laydate.render({
            elem: '#test1' //指定元素
        });
    </script>

    <script>
        //执行一个laydate实例
        laydate.render({
            elem: '#test2' //指定元素
        });
    </script>

{% endblock %}